# Language flags.
language: rust

# OS matrix.
os:
  - linux
  - osx
  # Fails due to cmake; Travis bug?
  # - windows

# Version matrix.
rust:
  - stable
  - beta
  - nightly

# Matrix modifications.
matrix:

  # Failures to allow.
  allow_failures:
    - rust: nightly

# Cargo package caching.
cache:
  cargo: true
