[package]
name = "runiq"
version = "0.1.0"
authors = ["Isaac Whitfield <iw@whitfin.io>"]
description = "An efficient way to filter duplicate lines from input, à la uniq."

[dependencies]
clap = "2.31"
twox-hash = "1.1"
